### ISSUE TITLE
Does it work on client side as well?

### ISSUE THREAD

**Issue by shkup** [jwaliszko/ExpressiveAnnotations#1]
Are these attributes support automatic generation of client side validation scripts? (Jquery validation rulset with sependency I assume...)

**Comment by JeremyRaj** [comment]
Hi Jaroslaw
  Awesome job. This works perfectly well in mvc 4. I am able to get the client validation to show up in the client but the custom error message does not show? It shows the default the field is required error message. Any idea why?

Appreciate your help.

Jeremy

**Comment by JaroslawWaliszko** [comment]
Hi, thanks. 
It's highly unlikely to face such an issue. Could you post your code? 
You could also take a look at the MVC sample project where I use custom messages and it behaves as expected - maybe there is some minor difference in the usage...? Maybe your browser cache is not refreshed (try `Ctrl+F5`)?. Hard to guess.

Regards

**Comment by JeremyRaj** [comment]
Hi Jaroslaw,
    I have got it to work. I put the string into a resource file and after a few tries the message is showing correctly. Maybe it was due to browser cache or something. Anyways all working fine now.Thank you so much. Great plugin
Jeremy

Date: Thu, 11 Jun 2015 03:36:27 -0700

**Comment by JaroslawWaliszko** [comment]
Hi,
Cool, good it works. Thanks for feedback.

Regards
