### ISSUE TITLE
Expression and fieldsmap data attributes not escaping quotation marks

### ISSUE THREAD

**Issue by kevinlrak** [jwaliszko/ExpressiveAnnotations#104]
I am using the requiredif attribute on two different pages in my MVC application. One spot works: it is specified as follows:
`[RequiredIf("Length(Password) > 0", AllowEmptyStrings = false, ErrorMessageResourceType = typeof(Resources.Messages), ErrorMessageResourceName = "OldPasswordRequired")]`
`string OldPassword { get; set; }`

and inspecting the rendered HTML reveals:
`data-val-requiredif-expression="&quot;Length(Password) > 0&quot;" data-val-requiredif-fieldsmap="{&quot;Password&quot;:&quot;string&quot;}"`

The other spot does not seem to work. It is specified as:
`[RequiredIf("UseForceHeater==true")]`
`int? ForceHeater { get; set; }`

and the rendered HTML reveals:
`data-val-requiredif-expression=""UseForceHeater==true"" data-val-requiredif-fieldsmap="{"UseForceHeater":"bool"}"`

The main difference here is that the quotation marks within the data attributes in the second (non-functional) example are not escaped.

Any ideas? Thanks!

**Comment by kevinlrak** [comment]
Never mind. I found the problem in one of our custom HtmlHelperExtensions. I doubt anybody else will have a similar problem.

**Comment by jwaliszko** [comment]
Thanks for update. Good it works.
