### ISSUE TITLE
Referencing properties of the parent model

### ISSUE THREAD

**Issue by FilipFilipov** [jwaliszko/ExpressiveAnnotations#105]
I have a complex model, part of which is a number scale that can have a collection of ranges defined. I want to make sure that the start and end of each range can't go outside the scale's limits, which are also adjustable. Everything in the dom is part of the same form, but the range needs to refer to the its parent's properties for this to work. Is that possible with this library or even hypothetically possible to implement?

**Comment by jwaliszko** [comment]
Is there anything stopping you from adding parent model reference to the current model and exposing it via property?

**Comment by FilipFilipov** [comment]
Well, the complete model is meant to be a C# wrapper for a JS widget configuration, so I'd rather not add any properties that are not part of the widget's api if I can.

**Comment by jwaliszko** [comment]
You need to somehow associate the instances. I do not see any possibility other than shown below, e.g.
```
class FirstType
{
    FirstType()
    {
        Child = new SecondType {Parent = this};
    }

    public SecondType Child { get; set; }
    public int Min { get; set; }
    public int Max { get; set; }
}

class SecondType
{
    public FirstType Parent { get; set; }

    [AssertThat("Value > Parent.Min && Value < Parent.Max")]
    public int Value { get; set; }
}
```
