### ISSUE TITLE
Custom function return value

### ISSUE THREAD

**Issue by samgiordano** [jwaliszko/ExpressiveAnnotations#106]
I have created a custom function to perform a certain check.  

[AssertThat("UnitsUsedWithinLimits(Resource_ID, Units_Used, Stop_Time, Start_Time)", ErrorMessage = " * Must be within the time span of Start and Stop")]

I am returning true if the condition is met (meaning it is valid) and false if it is not met but the error message shows either way.

**Comment by jwaliszko** [comment]
Due to the lack of details, I assume it is a client-side issue. Check web console output for errors. If you haven't provided client-side function equivalent, you're going to see this:

> ReferenceError: UnitsUsedWithinLimits is not defined(…)

I refer you to [this section](https://github.com/jwaliszko/ExpressiveAnnotations#what-if-there-is-no-built-in-function-i-need) of the documentation.

**Comment by samgiordano** [comment]
Hello,

Thank you for your response.  Maybe if I provide more info you can help me
figure out where I'm going wrong.  I am using client side and I do have the
function equivalent but maybe I have an issue there?  When I debug the
client side it is returning true if it passed the validation and false if
it did not but it keeps showing the validation message.

Here is the client side code:

ea.addMethod('UnitsUsedWithinLimits', function(Resource_ID, Units_Used,
Stop_Time, Start_Time) {
    var resourceID = @Html.Raw(Json.Encode(Model.Resource_ID));
    var startTime = $('#Start_Time').val();
    var stopTime = $('#Stop_Time').val();
    var unitsUsed = $('#Units_Used').val();
    $.get('/SAFPost/ValidateUnitsUsedWithinLimits', { resourceID:
resourceID, units: unitsUsed, stopTime: stopTime, startTime: startTime },
function (data) {
        return data;
    });
});

Maybe I am doing something wrong here?  I created the function definition
to match the server side definition and then I call my business layer
validation method and return true or false accordingly.

Thanks for any help.

Steve

**Comment by jwaliszko** [comment]
Now I see what is wrong. You've used async ajax call inside the method. Asynchronous validation is currently not supported, [as noted here](https://github.com/jwaliszko/ExpressiveAnnotations/tree/6fff1fd41ac2766c7eef5acf71de5a7421308d00#is-there-a-possibility-to-perform-asynchronous-validation). This topic has [been discussed here](https://github.com/jwaliszko/ExpressiveAnnotations/issues/73), as well as the possible workarounds.

**Comment by samgiordano** [comment]
I've tried setting it to an async call but I get the same result.  Do I
need to do the workaround by setting the return value to true initially?

On Mon, Mar 7, 2016 at 10:46 AM, Jarosław Waliszko <notifications@github.com

**Comment by jwaliszko** [comment]
You mean, to **sync** call?

**Comment by samgiordano** [comment]
Yes sorry I meant using the ajax call where I can set async to false.

On Mon, Mar 7, 2016 at 12:40 PM, Jarosław Waliszko <notifications@github.com

**Comment by jwaliszko** [comment]
It's unexpected.
Nevertheless sync ajax calls block UI so such a hack is obscure anyway.

Yes you could do that other thing as noted in the referenced post above. 

Natural solution would be to extend current EA functionality to support async validation but it is not a trivial task and requires some time which I do not currently have. Some work has been done [here, in async-work branch](https://github.com/jwaliszko/ExpressiveAnnotations/tree/async-work) but is not yet functional for some particular cases (e.g. multiple functions with the same signatures will fail).

**Comment by samgiordano** [comment]
Ok got it.  Thanks for all the help!

On Mon, Mar 7, 2016 at 12:47 PM, Jarosław Waliszko <notifications@github.com
