### ISSUE TITLE
Beginner issue:  Can't get client side validation to work

### ISSUE THREAD

**Issue by edhalsim** [jwaliszko/ExpressiveAnnotations#107]
I can't get RequiredIf validation in my ASP.NET MVC 5 application to fire on the client (it always posts back to the server).

I added the following to `Application_Start`
```
DataAnnotationsModelValidatorProvider.RegisterAdapter(
    typeof(RequiredIfAttribute), typeof(RequiredIfValidator));
DataAnnotationsModelValidatorProvider.RegisterAdapter(
    typeof(AssertThatAttribute), typeof(AssertThatValidator));
```
and my page contains the script reference to:  expressive.annotations.validate.js

I get the correct validation error messages, but it always posts back to the server to get them.

Thanks for any help;  I appreciate it.

**Comment by jwaliszko** [comment]
Are there any errors on the web console?

**Comment by edhalsim** [comment]
If you mean F12 console, no, not that I can see.

**Comment by jwaliszko** [comment]
If setup is done correctly (as described [in the doc](https://github.com/jwaliszko/ExpressiveAnnotations#what-about-the-support-of-aspnet-mvc-client-side-validation)), I assume that there can be an exception somewhere in your JavaScript, which aborts further client-side execution and forces post-back to the server.

The error, if any, should appear on console just before the request to the server is sent. If log is not preserved, whatever is catched there is cleared on page reload, as soon as response is received.

Ultimately, you can put breakpoint in expressive.annotations.validate.js, e.g. [here](https://github.com/jwaliszko/ExpressiveAnnotations/blob/adc4c9ed72f6da26607ac6e372529ae5d4dea3f4/src/expressive.annotations.validate.js#L666), and debug through it.

If you'll not be able to troubleshot that, provide more details - the version you're using, the usage cases or, preferably, a tiny sample?. Also, have you been tested the [sample project](https://github.com/jwaliszko/ExpressiveAnnotations/tree/master/src/ExpressiveAnnotations.MvcWebSample)?

**Comment by edhalsim** [comment]
Well this is odd.  If I set a breakpoint on line 666, it doesn't stop.  This is version 2.6.6.  Here's my model:
public class HomeIndexFormModel
    {
        [RequiredIf("city == null", ErrorMessage="Zip Code is required.")]
        [Display(Name = "Zip Code")]
        public string zipCode { get; set; }
        [Display(Name = "City")]
        public string city { get; set; }
    }

Global.asax.cs:
public class MvcApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            ModelBinders.Binders[typeof(DataTable)] = new DataTableModelBinder();

            DataAnnotationsModelValidatorProvider.RegisterAdapter(
                typeof(RequiredIfAttribute), typeof(RequiredIfValidator));
            DataAnnotationsModelValidatorProvider.RegisterAdapter(
                typeof(AssertThatAttribute), typeof(AssertThatValidator));
        }
    }

I'm sure I'm doing something dumb, I just can't find it.  Thanks again for the help.

**Comment by jwaliszko** [comment]
That part you've shown looks OK. You haven't shown the view, so I assume you're using standard HTML helpers provided by MVC framework, in the following manner, e.g.
```
@Html.TextBoxFor(model => model.zipCode)
@Html.ValidationMessageFor(model => model.zipCode)
...
```
and your HTML source is generated correctly, with all the `data-val-*` attributes used by EA at client, with correct names (the same as used in expressions), i.e.
```
<input data-val="true" 
       data-val-requiredif="Zip Code is required." 
       data-val-requiredif-allowempty="false" 
       data-val-requiredif-expression="&quot;city == null&quot;" 
       data-val-requiredif-fieldsmap="{&quot;city&quot;:&quot;string&quot;}" 
       name="zipCode" 
       id="zipCode"
       ...
```
What's more - which JavaScript libraries you have loaded on your page? Essential for EA to work are: *jquery.js*, *jquery.validate.js* and *jquery.validate.unobtrusive.js*, loaded in this particular order. 

If you have more libraries than that, maybe one of them interferes with the validation logic? Do a simple test - decorate `city` using built-in `[Required]` attribute:
```
[Required]
public string zipCode { get; set; }
```
and check if client-side validation is working for that particular case. If not, it means your problem is not related to EA.

**Comment by edhalsim** [comment]
Here's my generated HTML:
`<label for="zipCode">Zip Code</label>: 
<input data-val="true" 
       data-val-requiredif="Zip Code is required." 
       data-val-requiredif-allowempty="false" 
       data-val-requiredif-expression="&quot;city == null&quot;" 
       data-val-requiredif-fieldsmap="{&quot;city&quot;:&quot;string&quot;}" 
       id="zipCode" name="zipCode" type="text" value="" /> `

Here's the view:
`@model PharmacyProviderSearch.Models.HomeIndexFormModel

@{
    ViewBag.Title = "Home Page";
}

@using (Html.BeginForm("Index", "Providers"))
{
    @Html.ValidationSummary(false);
    <p>
        @Html.LabelFor(m => m.zipCode): @Html.TextBoxFor(m => m.zipCode) @Html.ValidationMessageFor(m => m.zipCode)<br />
        Or @Html.LabelFor(m => m.city): @Html.TextBoxFor(m => m.city) and State: @Html.DropDownListFor(m => m.state, Model.states, "")<br />
        <input type="submit" value="Search" />
    </p>
}

@section Scripts{
    <script src="/Scripts/jquery.validate.js"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="/Scripts/expressive.annotations.validate.js"></script>
}`

Here are the generated scripts:
`<script src="/Scripts/jquery-1.10.2.js"></script>

    <script src="/Scripts/jquery.validate.js"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="/Scripts/bootstrap.js"></script>
<script src="/Scripts/respond.js"></script>
    
    <script src="/Scripts/jquery.validate.js"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="/Scripts/expressive.annotations.validate.js"></script>`

If I use just [Required], it works (I don't get a postback).

**Comment by jwaliszko** [comment]
*jquery.validate.js* and *jquery.validate.unobtrusive.js* are loaded twice. Remove that redundancy and check then.

**Comment by edhalsim** [comment]
That was it!  Now it's working.  Thanks again!

**Comment by jwaliszko** [comment]
Good it works :) Regards.

**Comment by aryefasten** [comment]
I had the same issue (also a beginner), and this solved it
thanks.

**Comment by Ronny-azure-pipelines** [comment]
Give this https://lift-json2.github.io/luther5/ a read
