### ISSUE TITLE
client side validation not working on Requiredif in expressive annotations 2.6.6

### ISSUE THREAD

**Issue by lalitha2016** [jwaliszko/ExpressiveAnnotations#108]
Hi,
I am working on MVC and using jquery 2.1.1.
requiredif attribute client side validation not working on expressive annotations 2.6.6

any one help me to resolve this issue.

Many Thanks

**Comment by jwaliszko** [comment]
To troubleshoot your client-side issue, [take a look here](https://github.com/jwaliszko/ExpressiveAnnotations/issues/107).

**Comment by lalitha2016** [comment]
Hi thanks for your reply.

its works perfectly on other fields
but not on dropdown.

I have a form with checkbox and dropdown fields.
if checkbox is selected, dropdown should not validate
if checkbox is unselected, dropdown should validate.

but now, dropdown is validated even I select checkbox.
**Model:**
        [Display(Name = "Apply for all days.")]
        public bool ApplyforAllDays { get; set; }

        [Display(Name = "Select Day")]
        [RequiredIf("ApplyforAllDays==false", ErrorMessage = "Please select day from dropdown")]
        public short WeekdayId { get; set; }
**View:**
 <div class="form-group">
        @Html.LabelFor(m => m.WeekdayId, new { @class = "col-md-3 col-xs-12 control-label" })
        <div class="col-md-6 col-xs-12">
            @Html.DropDownListFor(m => m.WeekdayId, new SelectList(Model.WeekdaysList, "Key", "Value"), "Select Day", new { @class = "form-control cstm-dropdown" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ApplyforAllDays, new { @class = "col-md-3 col-xs-12 control-label" })
        <div class="col-md-6 col-xs-12">
            <label class="check">
                @Html.CheckBoxFor(m => m.ApplyforAllDays, new { @class = "icheckbox" })
            </label>
        </div>
    </div>

could you please help me to resolve this issue?

**Comment by jwaliszko** [comment]
Your expression is wrong. 
`short` is a **value type** - it's a struct, representing integral numeric type. Value of such a type is non-null. 
I refer you to the documentation and/or sample project.

**Comment by jwaliszko** [comment]
Answer updated.

**Comment by lalitha2016** [comment]
Thank you so much.
i changed code from short to short?
it is working fine now. 
Thanks
