### ISSUE TITLE
Client side validation issues with nullable fields

### ISSUE THREAD

**Issue by evdinursan** [jwaliszko/ExpressiveAnnotations#109]
Hi,

I have a very strange scenario which involves EA on the client side and I will try to explain it as clear as I could in order to be easy to reproduce.

I want to emphasize from the beginning that there is no issues in the backend part of the validation (I disabled the front-end validation and everything works like a charm).

First of all, I have a big form which contains also a list of items (invoices on which a payment can be assigned) and every item from my list has the following fields as part of the model:

        /// <summary>
        /// Gets or sets the amount to pay on given invoice.
        /// </summary>
        /// <value>
        /// The amount to pay on given invoice.
        /// </value>
        [UIHint("FormFieldStringTemplate")]
        [AdditionalMetadata("IsNumericMaskEnabled", true)]
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = true)]
        //[RequiredIf("PaymentToInvoiceExchangeRate != null", ErrorMessage = "Suma achitata: Camp obligatoriu.")]
        [AssertThat("AmountToPayOnGivenInvoice >= 0", ErrorMessage = "Suma achitata: Valoarea trebuie sa fie strict pozitiva.")]
        public decimal? AmountToPayOnGivenInvoice { get; set; }

        /// <summary>
        /// Gets or sets the payment to invoice exchange rate.
        /// </summary>
        /// <value>
        /// The payment to invoice exchange rate.
        /// </value>
        [UIHint("FormFieldStringTemplate")]
        [AdditionalMetadata("IsNumericMaskEnabled", true)]
        [AdditionalMetadata("NumericMaskDigits", 4)]
        //[RequiredIf("AmountToPayOnGivenInvoice != null && AmountToPayOnGivenInvoice > 0", ErrorMessage = "Curs valutar alocare plata: Camp obligatoriu.")]
        //[AssertThat("PaymentToInvoiceExchangeRate > 0", ErrorMessage = "Curs valutar alocare plata: Valoarea trebuie sa fie strict pozitiva.")]
        [DisplayFormat(DataFormatString = "{0:N4}", ApplyFormatInEditMode = true)]
        public decimal? PaymentToInvoiceExchangeRate { get; set; }

Initially when the list is displayed, the AmountToPayOnGivenInvoice is populated with the value 0 which is displayed as "0,00" (the culture that has been set, has the decimal separator as ","). When I'm submitting the form, the validation summary shows an error message for each row in my table with the error set in the model (that the value should be positive) - also in the console log I see the following error message:

```
DOM field SupplierInvoices[0].AmountToPayOnGivenInvoice value conversion to numeric failed. Given value was not recognized as a valid float.
https://....../expressive.annotations.validate.js
Line 85
```

I guess that is something wrong with the localization but I cannot figure it out.

Thank you.

**Comment by jwaliszko** [comment]
In EA, numeric fields are by default parsed using [`parseFloat`](http://ecma-international.org/ecma-262/5.1/#sec-15.1.2.3) ([see here](https://github.com/jwaliszko/ExpressiveAnnotations/blob/1d322d2a7f625cf07b21f910664c2cd4f21bdf19/src/expressive.annotations.validate.js#L298)). As noted in the specification, this function is designed to parse decimal literals, which [use dot](http://ecma-international.org/ecma-262/5.1/#sec-A.2) as decimal separators. This function ignores locale settings. To be able to parse your value, [define your custom value parser](https://github.com/jwaliszko/ExpressiveAnnotations#how-to-cope-with-values-of-custom-types), which is a feature of EA.

**Comment by evdinursan** [comment]
Thank you for your answer. I have a question though - considering the fact that this is only a front-end issue, do I have to follow all the steps described in your docs? Meaning, do I have to decorate all decimal fields in all my models with that attribute (ValueParser('customparser')]) or can I skip directly to the frontend part and somehow override your decimal parser?

Thank you.

**Comment by jwaliszko** [comment]
This `ValueParser` attribute gives a hint to client-side to use alternative way of parsing for that particular field which is decorated with it. Attribute is required to be applied to these fields only, which needs to be handled in some non-standard way. 

What is also described in the documentation, if **all** your numeric fields are localized at client-side, you can override the entire logic for all the fields without `ValueParser` annotations, like this:
```
<script>
    ea.addValueParser('numeric', function (value) {
        return ... // handle specified type (numeric, datetime, etc.) parsing on your own
    });
```

**Comment by evdinursan** [comment]
It's working like a charm....

First, I defined a global method:

`var customNumberParser = function() {};`

Then, when the globalize data is finished loading, I assigned the Globalize.numberParser to my method:

`customNumberParser = Globalize.numberParser();`

And then, accordingly to your instructions, I modified the numeric parser:
```
ea.addValueParser('numeric', function (value) {
    return customNumberParser(value);
});
```

Thank you very much for your help and also for your library!!!!
