### ISSUE TITLE
RequiredIf with array

### ISSUE THREAD

**Issue by AndyButland** [jwaliszko/ExpressiveAnnotations#11]
First thanks for a great extension - it's working really well for me, but I have one issue.

I have this on my view model:

```
    [RequiredIf("QuestionTypeAsString == 'SingleSelect' && Skipped == false && RefusedToAnswer == false", ErrorMessage = "Please complete the answer or select one of the options to skip the question")]
    public int[] SelectedOptionsAnswer { get; set; }
```

This is posted via a set of checkboxes or radio buttons in the view, and I want to make sure one is selected.

When I step through the code SelectedOptionsAnswer is null, but the model state is valid.  Is there a way to get this attribute working with arrays please?

**Comment by JaroslawWaliszko** [comment]
In the next version (**>= 2.6.1**), I'm planning to extend functionality a bit, and handle the issues like yours with the help of [value parsers](https://github.com/JaroslawWaliszko/ExpressiveAnnotations#how-to-cope-with-values-of-custom-types). In your particular case following solution could be given (it's not yet published idea, if you have any suggestions do not hesitate to give it here):
```
[RequiredIf("QuestionTypeAsString == 'SingleSelect' && Skipped == false && ... ")]
[AssertThat("ArrayLength(SelectedOptionsAnswer) > 0")]
[ValueParser("ArrayParser")]
public List<int> SelectedOptionsAnswer { get; set; }
```
server-side method:
```
public int ArrayLength(List<int> array)
{
    return array.Count;
}
```
client-side equivalent:
```
ea.addMethod('ArrayLength', function(array) {
    return array.length;
});
```
and finally, how your DOM field value should be understood (ea built-in parser does not handle values, which are distracted in multiple fields - like your checkbox-rendered array):
```
ea.addValueParser('ArrayParser', function(value, field) {
    // provide your custom parsing mechanism of the field value at client side 
    // parameters: value - raw data string extracted by default from DOM element
    //             field - DOM element name for which parser was invoked

    var array = $(':input[name="' + field + '"]').serializeArray();
    return array.length === 0 
              ? null    // if array is empty, return null for RequiredIf to complain
              : array;  // otherwise - return array object for the ArrayLength method to work on
});
```

**Comment by konstrui** [comment]
Is this idea already part of the library?

**Comment by JaroslawWaliszko** [comment]
Yes. It is there, together with usage example included in [sample project](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/master/src/ExpressiveAnnotations.MvcWebSample):

![image](https://cloud.githubusercontent.com/assets/1596462/9576587/4d0c100e-4fd9-11e5-956c-b5e1f7f138ab.png)

**Comment by konstrui** [comment]
So I need to add these attributes to make it work:

    [AssertThat("ArrayLength(GekozenAntwoorden) > 0")]
    [ValueParser("ArrayParser")]

And in the client-side script, these methods:
    
    ea.addValueParser('ArrayParser', function (value, field) { // provide your custom parsing mechanism of the field value at client side
        // parameters: value - raw data string extracted by default from DOM element
        //             field - DOM element name for which parser was invoked
        var array = $(':input[name="' + field + '"]').serializeArray();
        return array.length === 0
            ? null    // if array is empty, return null for RequiredIf to complain
            : array;  // otherwise - return array object for the ArrayLength method to work on
    });

    ea.addMethod('ArrayLength', function (array) {
        return array.length;
    });

Will it work with a int[] you think?

**Comment by JaroslawWaliszko** [comment]
It should work, provided that your generated html is correct. Correct means all that `data-val-assertthat-*` html attributes are there, properly generated by the html helper you're using (just like for any other input field), e.g.
```
<input
       data-val="true"
       data-val-assertthat="assertion failed message..."
       data-val-assertthat-expression="&quot;ArrayLength(GekozenAntwoorden) > 1&quot;"
       data-val-assertthat-fieldsmap="{&quot;GekozenAntwoorden&quot;:&quot;list`1&quot;}"
       data-val-assertthat-parsersmap="{&quot;GekozenAntwoorden&quot;:&quot;ArrayParser&quot;}"
```

**Comment by konstrui** [comment]
I think it will work for my situation, but I do have some problems setting up a checkbox list.
Your sample website is using the MvcCheckBoxList helpers, but I wanted to create it without that library.

Not sure why, but when I use:

    Html.CheckBoxList("GekozenAntwoorden", new { value = antwoord.id, id = antwoord.id }

The validation is working, but no values are inside my property on a POST.

When I use this approach:

    <input type="check" value="@antwoord.id" />

The values are there when I do a POST, but of course then the data-attributes are not rendered.

Not sure what would be the best approach here :( Suggestions?

**Comment by JaroslawWaliszko** [comment]
I'm afraid I don't know any straightforward way to do it, so I cannot help. It is possible that there is no any simple solution, and it may be the reason why someone has created such an extension. 

If you'll be able to find some time, try to debug through this helper and write your custom basic version, adjusted to your needs. If you'll succeed in searching for any alternative solution, or if you'll write simplified helper, share it here please. 

Thanks. Regards.

**Comment by konstrui** [comment]
I understand.
Regarding the solution in your sample project: does it have to be in combination with a RequiredIf attribute to trigger the AssertThat? If I only use the AssertThat attribute, it is not triggered client side. Only server side.

**Comment by konstrui** [comment]
OK, I have created a ArrayValid method like in your first example.

This is the server side code:

    [AssertThat("ArrayValid(GekozenAntwoorden)")]
    [ValueParser("ArrayParser")]
    public int?[] GekozenAntwoorden { get; set; }

    public bool ArrayValid(int?[] array)
    {
       return (array != null && array.Length > 0);
    }

This would be the view:

    int count = 1;
                        foreach (var a in vraag.Antwoorden)
                        {
                        <li>
                            <label>
                                <input type="checkbox" name="GekozenAntwoorden" value="@a.AntwoordNummer" id="@a.AntwoordNummer"
                                           @{if (Model.GekozenAntwoorden != null && Model.GekozenAntwoorden.Contains(int.Parse(a.AntwoordNummer.ToString())))
                                             {
                                                 <text> checked='checked' </text>
                                             }
                                           }
                                           @{
                                               if (count == 1)
                                               {
                                                   <text>
                                                       data-val-assertthat-parsersmap="{&quot;GekozenAntwoorden&quot;:&quot;ArrayParser&quot;}"
                                                       data-val-assertthat-fieldsmap="{&quot;GekozenAntwoorden&quot;:&quot;nullable`1[]&quot;}"
                                                       data-val-assertthat-expression="ArrayValid(GekozenAntwoorden)"
                                                       data-val-assertthat-constsmap="{}"
                                                       data-val-assertthat="[NL]RABL_GekozenAntwoorden_AssertThat"
                                                       data-val="true"
                                                   </text>
                                               }
                                           }
                                        />
                                @Html.Raw(a.AntwoordTekst)
                            </label>
                        </li>
                            count++;
                        }

These is the ea methods I've added:

     ea.addMethod('ArrayValid', function (array) {
        return (array != null && array.length > 0);
    });

So this works for a radiobutton list, but not for the checkboxes. It just isn't firing on the client. Server side this is working great.

Any ideas on how to get this working?

**Comment by JaroslawWaliszko** [comment]
Instead of referring to this particular example, I can only say that `RequiredIf` will be invoked only when value is `null`, `AssertThat` - when value is not `null`. It's the general rule which works the same way at both server- and client-side. 

Value parser is an *exceptional mechanism*, which helps to extract values from HTML, if default `$('field_selector').val()` is not enough. Its job is to parse the value at client-side only, because such a value can be distracted among multiple fields. It has nothing to do with server-side. Server-side just works on objects already serialized by some model binder, e.g. provided by MVC framework. 

When value parser returns `null` for an empty array, `AssertThat` will not be invoked. So, if you're not using `RequiredIf`, but `AsserThat` only, take that under consideration and parse the value accordingly - instead of `null` return empty array `[]`. 

For example (code is oversimplified to show the difference):

* here `RequiredIf` will be fired for an empty array (because `null` is returned that time):

 ```
ea.addValueParser('ArrayParser', function (value, field) {
        var array = ... // deserialize your DOM extracted value to array object
        return array.length === 0 ? null : array; 
});
```

* here forget about `RequiredIf`, only `AssertThat` will be invoked (`null` is never returned):

 ```
ea.addValueParser('ArrayParser', function (value, field) {
        var array = ... // deserialize your DOM extracted value to array object
        return array === null ? [] : array; 
});
```

I know that it is not that obvious, and can introduce some confusion at the beginning. To understand it better I can advice to debug through it few times, the good starting points are here:

![image](https://cloud.githubusercontent.com/assets/1596462/9606243/901f7482-50c2-11e5-952e-95550ae84f05.png)

In the end - the `data-val-*` attributes, written by hand, are a bit hacky for me. They suppose to be generated automatically by some helpers. Otherwise, if you'll change your expression, such an attributes are required to be manually updated as well. If you'd ask me, I'd leave client-side validation and relay only on server side one in some exceptional cases.

Regards
