### ISSUE TITLE
ExpressiveAnnotations client side validation conflict with jquery mask for thousand separator

### ISSUE THREAD

**Issue by h4m3d66** [jwaliszko/ExpressiveAnnotations#112]
I use jquery.mask for moeny fileds and also use ExpressiveAnnotations for a field like:
`[AssertThat("Investment>=1000000", ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "InvestmentCanNotBeLessThanOneMillionRial")]`
In this situation beacause of ',' character in the input and ExpressiveAnnotations is added, the field validation is activated

**Comment by jwaliszko** [comment]
I assume you have parsing issue due to usage of comma, instead of period, as a decimal separator. See this thread for a solution: https://github.com/jwaliszko/ExpressiveAnnotations/issues/109.

**Comment by h4m3d66** [comment]
it is not for decimal separator, It is for thousand separator, and I dont have decimal separator at all.
based on your solution I use 
` <script type="text/javascript">
        ea.addValueParser('text', function (value) {
            return value.replace(',', '');
        });`
but its give me this error:
`DOM field Investment value conversion to numeric failed. Given value was not recognized as a valid float.`

**Comment by jwaliszko** [comment]
In such case you should write your [custom](https://github.com/jwaliszko/ExpressiveAnnotations#what-if-there-is-no-built-in-function-i-need) validation function.

**Comment by h4m3d66** [comment]
based on the solution I have changed my model to :
`public bool IsInvestmentMoreThanOneMillionRial(long? investment)
        {
            return long.Parse(investment.Value.ToString().Replace(",",""))>1000000;
        }

        [Display(ResourceType = typeof(Resource), Name = "Investment")]
        [RequiredIf("CompanyTypeID==Guid('80124f30-0936-bfe1-d3b8-1651af2d4b3e')", ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "RequiredFieldMessage")]
        [AssertThat("IsInvestmentMoreThanOneMillionRial(Investment)")] `

and in view:
`ea.addMethod('IsInvestmentMoreThanOneMillionRial', function (investment) {
            var removeComma = investment.toString().replace(',', '');
            var parsed = parseFloat(removeComma);
            return parsed > 1000000;
        });`

but it gave me this error:
[expressive.annotations.validate.js:85 DOM field Investment value conversion to numeric failed. Given value was not recognized as a valid float.](url)

**Comment by jwaliszko** [comment]
The error is justified because custom client side methods (unlike the value parsers), have arguments already converted according to their types (`numeric` in your case, because `investment` is of `long?` type). And your conversion fails because `parseFloat` does not recognize comma separated numbers e.g. `123,123,123` as a valid literal.

You need to use `string`, i.e.
```
[AssertThat("IsGreaterThan(Investment, 1000000)")]
public string Investment { get; set; }

public bool IsGreaterThan(string investment, int treshold)
{
    return long.Parse(investment.Replace(",", "")) > treshold;
}
```
and client:
```
ea.addMethod('IsGreaterThan', function (value, treshold) {
    // arguments converted: typeof value - "string", typeof treshold - "number"
    return parseFloat(value.replace(/,/g , '')) > treshold;
});
```

**Comment by h4m3d66** [comment]
Thanks a lot. its working
