### ISSUE TITLE
Server error when using two [AssertThat]

### ISSUE THREAD

**Issue by ruant** [jwaliszko/ExpressiveAnnotations#113]
Was working fine in in version 2.6.5, but after I updated to version 2.6.8 this happens.
If I remove one of the AssertThat on the model, doesn't mater which, it works again.
But I need to test both scenarios..

Since the rest of the files updated, the jquery stuff, is only client side and this happens at server side I guess there is something wrong with ExpressiveAnnotations?

ERROR:
> Validation type names in unobtrusive client validation rules must be unique. The following validation type was seen more than once: assertthata

HTML:
```
<div class="floating-field--wrapper checkout-address-form-postalcode">
  @Html.LabelFor(x => x.Customer.Address.PostCode)
  @Html.TextBoxFor(x => x.Customer.Address.PostCode, new { value = Model.Customer.Address.PostCode, placeholder = "Postal code" })
  @Html.ValidationMessageFor(x => x.Customer.Address.PostCode)
</div>
```

Model:

```
[RequiredIf("UseAddress == true", ErrorMessage = "Postal code is required")]
[AssertThat("Length(PostCode) == 4 && IsNumber(PostCode)", ErrorMessage = "Have to be 4 digits")]
[AssertThat("CompareOrdinal(City, 'Invalid postal code') != 0", ErrorMessage = "Invalid postal code")]
[Display(Name = "Postal code")]
public string PostCode { get; set; }
```

**Comment by jwaliszko** [comment]
Unfortunately, without a self-contained, minimal, reproducible test case there's not much I can do about this bug report right now due to the lack of time. Provide me reproducible sample (your model works for me) so I can fix this faster.

**Comment by jwaliszko** [comment]
I've found the reproducible scenario. I'll try to fix that sometime soon hopefully.

**Comment by jwaliszko** [comment]
Fixed and unit-tested here: https://github.com/jwaliszko/ExpressiveAnnotations/commit/5e42f77f118ad8be26a6f82af3b4b8eb94a8c290. When you find some spare time kindly retest it please.

**Comment by ruant** [comment]
Wow, that was quick @jwaliszko ! :speedboat: :speedboat: 
I pulled down the commit and ran the WebSample test, I also added it to my own project and tested it there and it seams to be working perfectly again :+1: 

Thanks for making this awesome software. Keep up the good work!

**Comment by jwaliszko** [comment]
Good it works. Thanks for reporting this and retest.
