### ISSUE TITLE
Using Guid in RequiredIf

### ISSUE THREAD

**Issue by ssteiner** [jwaliszko/ExpressiveAnnotations#114]
Hi

I've adorned a property my model with the following constraint

    [RequiredIf("NodeId != Guid(00000000-0000-0000-0000-000000000000)")]
    public string DefaultCostCenter { get; set; }

I'd assume that in case my model Properlty NodeId == Guid.Empty, I'd get no validation error.. but that is not the case. Am I using the wrong syntax?

Thanks

**Comment by jwaliszko** [comment]
Syntax is wrong, as noted in documentation regarding [built-in functions](https://github.com/jwaliszko/ExpressiveAnnotations#built-in-functions) `Guid(string str)` accepts string literal, so `Guid('00000000-0000-0000-0000-000000000000')` is what you need.
