### ISSUE TITLE
Possible to Check Validation State?

### ISSUE THREAD

**Issue by Rumple-Phillip** [jwaliszko/ExpressiveAnnotations#117]
May be a stupid question, but is it possible to check the validation state after the validation has been ran?  Ergo, we want our submit button disabled (which we can do with jquery) when clicked, and not be clickable again unless the validation fails.  This helps prevent multiple submissions into our system. But, for the life of me, I can't figure out how to query the state of the client side validation :/

**Comment by jwaliszko** [comment]
If I understand you correctly, are you looking for [`jquery.valid()`](https://jqueryvalidation.org/valid) method? Calling this function checks whether the selected form is valid, or whether all selected elements are valid, i.e. 
```
var isValid = $('form').valid();
``` 
This call will re-validate your form though. If the form has been already processed by validation function, you can call this one instead if you do not wish the re-validation to trigger, i.e 
```
var validator = $('form').validate(); // gets validator object attached to the form
var isValid = validator.numberOfInvalids() === 0;
```
