### ISSUE TITLE
Validation with Hidden Checkbox

### ISSUE THREAD

**Issue by madrianr** [jwaliszko/ExpressiveAnnotations#119]
Hello,
is it possible to add validation on a Datetime field which is based on a Checkbox Value (chkRuhendmeldungVorhanden) of a hidden field?

`      [RequiredIf("chkRuhendmeldungVorhanden == true", ErrorMessage = "Sie müssen ein Wiederbetriebsdatum eingeben.")]
public DateTime? Personenbetreuer_Wiederbetriebsdatum1 { get; set; }
`

if the checkbox "chkRuhendmeldungVorhanden" is visible it works but if I set it to hidden it doesn't work:
@Html.HiddenFor(model => model.chkRuhendmeldungVorhanden, new { htmlAttributes = new { @class = "form-control" } })

robert

robert

**Comment by jwaliszko** [comment]
Hi, it should work without problems. Maybe the hidden template you are using is your custom one, and overrides the default name of the field? Check the web console output for any warnings. The output HTML  should be reassembled into this in your case:
```
<input 
    data-val="true" 
    data-val-required="Sie müssen ein Wiederbetriebsdatum eingeben." 
    id="chkRuhendmeldungVorhanden" 
    name="GoAchkRuhendmeldungVorhandenroad" 
    type="hidden" 
    ...
```

**Comment by jwaliszko** [comment]
If you have some time provide me please self-contained, minimal, reproducible test case so I can help you.

**Comment by madrianr** [comment]
Hi,

 

I use:

@Html.HiddenFor(model => model.chkRuhendmeldungVorhanden, new { htmlAttributes = new { @class = "form-control" } })

 

and this code creates:

 

 

 

 

might be a problem that this is a hidden Input with data-val=true and Value=False instead of a checkbox?

 

robert

 

Von: Jarosław Waliszko [mailto:notifications@github.com] 
Gesendet: Sonntag, 24. April 2016 20:01
An: jwaliszko/ExpressiveAnnotations
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [jwaliszko/ExpressiveAnnotations] Validation with Hidden Checkbox (#119)

 

If you have some time provide me please self-contained, minimal, reproducible test case so I can help you.

**Comment by jwaliszko** [comment]
Your message seems to be incomplete, please use GitHub instead of direct reply:
![image](https://cloud.githubusercontent.com/assets/1596462/14781717/7d808a0a-0ae4-11e6-83e0-00ae82abd76d.png)

**Comment by madrianr** [comment]
found it - in Javascript I have to use  $('#chkRuhendmeldungVorhanden').val(true); to assign a value to the <Input> field...

robert

**Comment by jwaliszko** [comment]
Ok, so your `chkRuhendmeldungVorhanden` property is of `Nullable<bool>` type. When uninitialized, it is interpreted as `null`. The result of the expression `null == true` is always `false` since a value of type `bool` is never equal to `null` of type `bool?`.

Instead of setting the  field value in JS, you can either change the type to `bool`, or initialize the model before sending to client.

It has nothing to do with visibility of the control.

**Comment by madrianr** [comment]
Thank you…

 

robert

 

Von: Jarosław Waliszko [mailto:notifications@github.com] 
Gesendet: Montag, 25. April 2016 15:47
An: jwaliszko/ExpressiveAnnotations
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [jwaliszko/ExpressiveAnnotations] Validation with Hidden Checkbox (#119)

 

Ok, so your chkRuhendmeldungVorhanden property is of Nullable<bool> type. When uninitialized, it is interpreted as null. The result of the expression null == true is always false since a value of type bool is never equal to null of type bool?.

Instead of setting the field value in JS, you can either change the type to bool, or initialize the model before sending to client.

It has nothing to do with visibility of the control.
