### ISSUE TITLE
custom property with RequiredIf

### ISSUE THREAD

**Issue by JasonLounsbery** [jwaliszko/ExpressiveAnnotations#126]
I have a property that determines if a field is required.  It always says it is required

        [DataMember]
         [Description("Address Line 1")]
        [RequiredIf("isRequired(ADDRESS,'STREET') == true", ErrorMessage="Address is Required")]
        public string ADDRESS { get; set; }

[DataMember]
         [Description("Address Line 2")]
         [RequiredIf("isRequired(ADDRESS2,'STREET2') ", ErrorMessage = "Address is Required")]
        public string ADDRESS2 { get; set; }

 public bool isRequired(string value,string FieldName)
        {
            return false;
          
        }
I removed the code for IsRequired so it always returns false

ADDRESS and ADDRESS2 are always required.  Can something like this be done?

**Comment by jwaliszko** [comment]
I'm afraid I cannot help you because your question doesn't define what the problem is.

**Comment by JasonLounsbery** [comment]
The issue is that the properties are being flagged as required regardless of what IsRequired is returning.  I thought that the RequiredIf attribute would reflect what ever the function IsRequired returned. If IsRequred returns True and the Address field is blank, the error message shows up.  if IsRequred returns False, and the Address field is blank, the error message shows up.

**Comment by JasonLounsbery** [comment]
The issue is that the properties are being flagged as required regardless of what IsRequired is returning. I thought that the RequiredIf attribute would reflect what ever the function IsRequired returned. If IsRequred returns True and the Address2 field is blank, the error message shows up. if IsRequred returns False, and the Address2 field is blank, the error message shows up.

Here is my code.  For testing I have isRequired returning false.


…Model

[DataMember]
[Description("Address Line 2")]
[RequiredIf("isRequired(ADDRESS2,'STREET2') ", ErrorMessage = "Address is Required")]
public string ADDRESS2 { get; set; }

public bool isRequired(string value,string FieldName)
{
return false;
         }



Jason Lounsbery
GEMMS
10201 N. Illinois Street
Suite 140
Indianapolis, IN 46290
www.gemmsnet.com
Ph:   317-819-5060
Ph:   800-773-3111
Fax: 317-819-5071

---------------- --------------------------------
The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in relation to the contents of this information is strictly prohibited and may be unlawful. Neither the sender nor the represented institution are liable for the correct and complete transmission of the contents of an e-mail, or for its timely receipt.
------------------------------------------------

**Comment by jwaliszko** [comment]
You should probably take a look at the documentation related to [defining your own methods](https://github.com/jwaliszko/ExpressiveAnnotations/tree/bcdfaef599ad9644344170031042710b765af984#what-if-there-is-no-built-in-function-i-need) - if you are using client-side validation you need to define respective method at client-side as well. I assume you have an error related to undefined reference - check your [web console output](https://github.com/jwaliszko/ExpressiveAnnotations/tree/bcdfaef599ad9644344170031042710b765af984#can-i-increase-web-console-verbosity-for-debug-purposes).
