### ISSUE TITLE
JavaScript runtime error: Unable to get property 'substr' of undefined or null reference

### ISSUE THREAD

**Issue by philvbprogrammer** [jwaliszko/ExpressiveAnnotations#144]
Hi I keep getting this when running my MVC 5 page

Exception was thrown at line 492, column 13 in http://localhost:36849/Scripts/expressive.annotations.validate.js
0x800a138f - JavaScript runtime error: Unable to get property 'substr' of undefined or null reference

which refers to:
 ```
   getPrefix: function(value) {
            return value.substr(0, value.lastIndexOf('.') + 1);
        }
```

the value passed is null so fails, is this a bug or what do i need to do in order to pass a value to getPrefix?

Thanks
Phil

**Comment by philvbprogrammer** [comment]
actually it was undefined.
i modded my js to be 
```
 getPrefix: function (value) {
            if (value !== undefined && value !== null) {
                return value.substr(0, value.lastIndexOf('.') + 1);
            }
```
and this has fixed it

**Comment by jwaliszko** [comment]
While this fix is reasonable, it does not explain the source of the problem - mainly why there is no names on your input fields? EA demands the names to exist - based on them it is able to lookup for a particular field and extract value of it when needed.

BTW: You've provided link pointing to your localhost.

**Comment by philvbprogrammer** [comment]
aha, the name does exist in the HTML markup, BUT it is a custom strongly-typed htmlhelper i wrote which uses a div as the container then multiple checkboxes inside.
due to it being a div you cannot access the name attribute via element.name....mmmm so how can i do this....as a span would have the same issue.
any ideas?

Phil

**Comment by jwaliszko** [comment]
I don't know what you're trying to achieve since you provided no details.
