### ISSUE TITLE
Operator '+' cannot be applied to operands of type 'System.Byte'

### ISSUE THREAD

**Issue by DavidMorg** [jwaliszko/ExpressiveAnnotations#145]
Since upgrading from version 2.7.3 to version 2.9.1, I'm now getting error: Operator '+' cannot be applied to operands of type 'System.Byte'.

Bye is a value between 0 and 255 and therefore should allow numerical operations. 

By the way, love this plugin

**Comment by jwaliszko** [comment]
Thanks for reporting this - will be fixed in next release.

**Comment by jwaliszko** [comment]
Fix proposed here: https://github.com/jwaliszko/ExpressiveAnnotations/commit/75fb3f469ff5b2fe635bfdc2eeda038d741cff8c.
