### ISSUE TITLE
Class methods in RequiredIf Expression

### ISSUE THREAD

**Issue by gigjacker** [jwaliszko/ExpressiveAnnotations#146]
Hi - I'm perfectly happy to boil this down to short reproducible example if need be but I think this will probably be quite easy for you to see what I'm doing wrong.

Model
```
public class MyModel
{
     [RequiredIf("IsMyEnumValueCondition()"]
     public MyEnum MyEnumValue { get; set; }
  
     [RequiredIf("IsMyEnumValueCondition() && My2ndEnumValueIn(My2ndEnum.Opened, My2ndEnum.InProgress")]
     public My2ndEnum My2ndEnumValue { get; set; }

     public bool IsMyEnumValueCondition()
     {
            return (this.MyEnumValue == MyEnum.First ||
                 this.MyEnumValue == MyEnum.Second);
     }

     public bool My2ndEnumValueIn(params My2ndEnum[] my2ndEnumList)
     {
            return my2ndEnumList.Any(x => x == My2ndEnumValue);
     }
}
```

Enums
```
public enum MyEnum
{
     First,
     Second, 
     Third
}

public enum My2ndEnum
{
    Opened,
    InProgress,
    Closed
}
```

I'm getting an InvalidToken exception thrown.  Is this sort of thing just not allowed or am I missing something?

Cheers,
.pd.

**Comment by jwaliszko** [comment]
Hi, I see no error in your solution. It should work. Maybe there is a bug in EA. Do you have a complete stack trace? I cannot help, nor fix, anything now since my notebook has crashed. I'm looking for a new one. It can take up to 2 weeks.

**Comment by jwaliszko** [comment]
OK I thing I see the error - there is no closing bracket at the end of your expression, this should work:
`[RequiredIf("IsMyEnumValueCondition() && My2ndEnumValueIn(My2ndEnum.Opened, My2ndEnum.InProgress)")]`

**Comment by jwaliszko** [comment]
OK, I think I actually see the error - there is no closing bracket in `My2ndEnumValueIn()` function at the end of your expression, this should work:
```
[RequiredIf(@"IsMyEnumValueCondition() 
              && My2ndEnumValueIn(My2ndEnum.Opened, My2ndEnum.InProgress)")]
```
BTW: the exception denotes which attribute has the broken expression, and points out the error position (line, column) in the expression.

**Comment by gigjacker** [comment]
Hi - thanks for getting to back to me.  I'll put together a small reproducer.
