### ISSUE TITLE
ExpressiveAnnotations and JqueryUI Datepicker anomoly

### ISSUE THREAD

**Issue by jwstemper** [jwaliszko/ExpressiveAnnotations#158]
When I use the JQueryUI datepicker widget on a date field that was created with the following annotation the client side validation is not triggered until I click in some other field, return to the date field and then exit.  
```
     [AssertThat("ResolutionDate<=Today()", ErrorMessage = "Resolution date can not be in the future.")]
     [AssertThat("ResolutionDate>=DateReceived", ErrorMessage = "Resolution date must be after the date received.")]
     [DataType(DataType.Date)]
      public DateTime? ResolutionDate { get; set; }
```
I'm assuming some sort of event is missed.  Any ideas or fixes?

**Comment by jwaliszko** [comment]
I think you could try to encourage the datepicker to execute the form validation as soon as the date selection is performed, e.g.
```
$('.date').datepicker().on('change', function() {
    $(this).valid(); // validate on change (happens prior to unfocus)
});
```

In the sample project (Home.cshtml view in particular) similar approach is used.
