### ISSUE TITLE
RequiredIfAttribute has no effect when applied to a field of non-nullable value type 'System.Boolean'

### ISSUE THREAD

**Issue by matmiranda** [jwaliszko/ExpressiveAnnotations#162]
Please check link of stackoverflow: 

http://stackoverflow.com/questions/44076590/requiredifattribute-has-no-effect-when-applied-to-a-field-of-non-nullable-value

Code:

_**Model:**_

```
[Display(Name = "Checkbox name")]
[RequiredIf("test == false", ErrorMessage = "test message error")]
public bool test { get; set; }
```
_**View:**_

```
<div>
    @Html.LabelFor(x => x.test)
    @Html.CheckBoxFor(x => x.test)
    @Html.ValidationMessageFor(x => x.test)
</div>
```

**First attempt:**

`public bool? test { get; set; }`

Error: 

> Can not implicitly convert type "bool?" In "bool". Is there an explicit cast (is there a missing cast?)

**Second attempt:**

`@Html.CheckBoxFor(x => x.test ?? false)`

Error:

> Templates can be used only with expressions of field access, property access, single-dimension array index, or single-parameter standardized indexer.

**Three attempt:**

**_Model:_**
```
[Display(Name = "Checkbox name")]
[AssertThat("test == false", ErrorMessage = "test message error")]
public bool test { get; set; }
```
**_View:_**

```
<div>
 @Html.LabelFor(x => x.test)
 @Html.CheckBoxFor(m => m.test)
 @Html.ValidationMessageFor(x => x.test)
</div>
```
Third attempt, nothing happens! What did I do wrong ?

Any Solution ?

**Comment by jwaliszko** [comment]
As [denoted](https://github.com/jwaliszko/ExpressiveAnnotations#requiredif-vs-assertthat---where-is-the-difference) in the docs, `AssertThat` is what works for non-nullable fields.

**Comment by matmiranda** [comment]
@jwaliszko The problem has disappeared, but the error message is not displayed in view.

**Comment by matmiranda** [comment]
@jwaliszko I updated my post, please look at the third attempt.

**Comment by jwaliszko** [comment]
Are you sure `AssertThat("test == false")` is what you need? From the context of how you wanted to use `RequiredIf` I assume `AssertThat("test")` is simply enough. Message will appear when validation is triggered. Do you face any errors on the web console? Do you need client-side validation as well? If so, are the scripts attached on the page? Please take a look at the MVC sample project, I believe you can find some usefull examples there.

**Comment by matmiranda** [comment]
@jwaliszko 

Are you sure AssertThat("test == false") is what you need? _Yes_

Do you face any errors on the web console? _No_

Do you need client-side validation as well? _Yes_

If so, are the scripts attached on the page? _Yes_

I already did test with string works perfectly.

The test I did:

`"stringempty == null"` -----> Works right.

I have 4 checkbox, one of them must be checked, that is my need. How can I do this ?

**Comment by jwaliszko** [comment]
```
[AssertThat("test1 || test2 || test3 || test4", ErrorMessage = "check at least one")]
public bool test1 { get; set; }
public bool test2 { get; set; }
public bool test3 { get; set; }
public bool test4 { get; set; }
```
```
@Html.ValidationMessageFor(model => model.test1)
@Html.CheckBoxFor(model => model.test1)
@Html.CheckBoxFor(model => model.test2)
@Html.CheckBoxFor(model => model.test3)
@Html.CheckBoxFor(model => model.test4)
```

Just an example above. You can apply this attribute to each prop (e.g. to have it all highlighted in the view). You can also print the validation message for every prop if you wish.

**Comment by matmiranda** [comment]
Tank you, solved problem.

**Comment by jwaliszko** [comment]
You're welcome.
