### ISSUE TITLE
Validating using static method from another class

### ISSUE THREAD

**Issue by paulodiogo** [jwaliszko/ExpressiveAnnotations#165]
Firstly thanks for your library it has already saved me pain and is pretty nice.

I have this situation:
```

public class X
{
    public static bool IsValid(string y)
    {
        //return if y is valid
    }
 }

public class XViewModel
{
    [AssertThat("X.IsValid(Y)", ErrorMessage = "Y is invalid.")]
    public string Y { get; set; }
        
}
```
This situation can be possible some day?

**Comment by jwaliszko** [comment]
Hi, in theory nothing prevents us from extending the functionality in the appointed direction, but is it necessary? I know it's not the same but the simple workaround is as follows:
```
public class X
{
    public static bool IsValid(string y)
    {
        //return if y is valid
    }
 }

public class XViewModel
{
    [AssertThat("IsValid(Y)", ErrorMessage = "Y is invalid.")]
    public string Y { get; set; }
        
    public bool IsValid(string y)
    {
        return X.IsValid(y);
    }
}
```
Extending the functionality will introduce further complexity and is not going to work out-of-the-box at the client side. While there is no problem with server-side, at client there is no `X` context available, so the expression evaluation will fail. It would require some additional extensions at client, e.g.
```
ea.addSubModel({
    X: {
        IsValid: function (val) {
            // return ...
        }
    }
});
```

**Comment by paulodiogo** [comment]
Hi, thanks for the response, I did exactly that workaround. =D
