### ISSUE TITLE
Require at least x checkboxes

### ISSUE THREAD

**Issue by gdycus** [jwaliszko/ExpressiveAnnotations#169]
I have multiple checkbox and I concatenate a comma delimited string of the selected checkbox values. Ideas on how to require the user to select at least 2 checkboxes?

**Comment by jwaliszko** [comment]
Hi, what have you tried?

**Comment by gdycus** [comment]
Only 1 comma was required so I was able to use Contains.

Thanks!

On Aug 22, 2017, at 2:46 AM, Jarosław Waliszko <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, what have you tried?
