### ISSUE TITLE
Requiered if a value is given...  

### ISSUE THREAD

**Issue by ghost** [jwaliszko/ExpressiveAnnotations#184]
How to use like this.. 

[RequiredIf("ORG_BY_CD", "5", ErrorMessage = "Coordinator ID is required")] // This means: IF 'ORG_BY_CD' is equal 5 (for the example)  > make 'COR_CI_ID_NUM' required and apply its all validation / data annotations
 public string COR_CI_ID_NUM { get; set; }

thaks...

**Comment by jwaliszko** [comment]
Please refer to the [docummentation](https://github.com/jwaliszko/ExpressiveAnnotations/blob/master/README.md), the most straightforward cases are covered there.
