### ISSUE TITLE
AssertThat doesn't take in consideration the custom or overriden value parsers

### ISSUE THREAD

**Issue by evdinursan** [jwaliszko/ExpressiveAnnotations#188]
Hi,

Awhile ago I had an issue (https://github.com/jwaliszko/ExpressiveAnnotations/issues/109) that was solved by a simple javascript 3 lines method.

Now, I discovered something very strange and maybe I'm doing something wrong because otherwise I cannot explain this.

I have a custom value parser method defined:

```
ea.addValueParser('numeric', function (value) {
    return customNumberParser(value);
});
```

That thing works great, but if I'm adding an AssertThat attribute like this:

`[AssertThat("ServiceValueDiscount == null || ServiceValueDiscount <= NullableServiceContractedPrice", ErrorMessage = "You have an issue.")]`

I'm getting this error:

[fail] (14:04:00): DOM field NullableServiceContractedPrice value conversion to number failed. Given value was not recognized as a valid number.

If I'm taking out the AssertThat attribute, the validation works great. Am I missing something or do you have any idea what is wrong?

Thanks.
Evdin

**Comment by jwaliszko** [comment]
Hi, 
unfortunately in the meantime backward compatibility was broken. Instead of `numeric` please use `number`, i.e.
```
ea.addValueParser('number', function (value) {
    return customNumberParser(value);
});
```
Please excuse this issue. I need to prevent such a mistakes by further tests.
Regards

**Comment by evdinursan** [comment]
Thank you!!! I will test and I will get back!

dum., 8 iul. 2018, 12:31 Jarosław Waliszko <notifications@github.com> a
scris:

**Comment by evdinursan** [comment]
It's working perfectly. Thank you very much!
