### ISSUE TITLE
Javascript date comparison does not take into account (UK) format of input string

### ISSUE THREAD

**Issue by checkinnuggets** [jwaliszko/ExpressiveAnnotations#25]
Not sure this is exactly a bug in your code, perhaps something you hadn't considered or came across so far...

In expressive.annotations.validate.js, line 62, where the string value coming from the input is passed to Date.parse(), if that string is in UK format (DD/MM/YYYY), Date.parse successfully returns a numeric milisecond value which is then successfully used to create a date object.  The code does not error, but the date object returned does not have the expected value.

The specific problem I had here was that I was comparing two date fields, one >= the other, and with these resulting incorrect dates it gave the impression that sometimes the validation was working and sometimes it was not.

I can work around this temporarily by switching the 'DD' and 'MM' components of my 'value' string between the existing lines 61 and 62 as in my application all dates use that format.

**Comment by JaroslawWaliszko** [comment]
For next version (2.6.0) I'm planning to slightly modify the logic. Instead of `parseDate` and `parseObject` methods to be implemented, there will be only one method, mainly `parseValue` - to be overridden, e.g.:
```
<script>
    ea.settings.parseValue = function(value, type, defaultParseCallback) {
        switch (type) {
            case 'sometype': // handle value of this type on your own
                return ...
            default: // finally, for other types, do not forget...
                return defaultParseCallback(value, type); // ...to run the built-in logic
        }
    }
```
In case of your UK format issue, the solution can be following:
```
<script>
    ea.settings.parseValue = function(value, type, defaultParseCallback) {
        switch (type) {
            case 'datetime':
                var arr = value.split('/');
                var date = new Date(arr[2], arr[1] - 1, arr[0]);
                return date.getTime();
            default:
                return defaultParseCallback(value, type);
        }
    }
```
The advantage over current approach - parsing possibility will be given for any custom type (not only for `datetime` and generic `object` containing all non-simple types). I hope it will be more flexible.

**Comment by JaroslawWaliszko** [comment]
The idea has changed after a few discussions. The planned modification in 2.6.0, in your case, will be as follows:
 * at server-side decorate your date property with special attribute which gives a hint to client-side, which parser should be chosen for corresponding DOM field value deserialization:
    ```
    class Model
    {
        [ValueParser('ukdateparser')]
        public CustomType SomeField { get; set; }
```

 * at client-side register such a parser:
    ```
    <script>
        ea.addValueParser('ukdateparser', function(value) 
            var arr = value.split('/');
            var date = new Date(arr[2], arr[1] - 1, arr[0]);
            return date.getTime();
    });
```

Regards
