### ISSUE TITLE
AssertThat not triggering client-side

### ISSUE THREAD

**Issue by d-miles** [jwaliszko/ExpressiveAnnotations#89]
Hi, I'm having trouble combining `AssertThat` with `RequiredIf` on the client-side *only*. I've seen lots of examples to base my code off of, but I just don't seem to see the same results as anyone else. `RequiredIf` works great throughout my app though (client-side and server-side) -- `AssertThat` only works on the server-side. Here's what I'm trying to do...

My model:

    [RequiredIf("HasTownshipSurvey == false && HasSubdivisionPlan == false")]
    [AssertThat("HasCivicAddress == true",
            ErrorMessage = "You must provide at least one type of site descriptor")]*/
    public bool HasCivicAddress { get; set; }

    [RequiredIf("HasCivicAddress == false && HasSubdivisionPlan == false")]
    [AssertThat("HasTownshipSurvey == true",
            ErrorMessage = "You must provide at least one type of site descriptor")]*/
    public bool HasTownshipSurvey { get; set; }

    [RequiredIf("HasTownshipSurvey == false && HasSubdivisionPlan == false")]
    [AssertThat("HasSubdivisionPlan == true",
            ErrorMessage = "You must provide at least one type of site descriptor")]*/
    public bool HasSubdivisionPlan { get; set; }

I have each boolean field above defined in my view like so:

    @Html.HiddenFor(x => x.HasTownshipSurvey)

The value of the hidden field is controlled with JavaScript and the result to the server IS correct. Also, if I use these fields inside of a `RequiredIf` condition on another field (I am already), the fields are validated as expected on the client-side. I just don't get anything at all with `AssertThat` on the client-side.

Any ideas? Am I doing something horribly wrong? I'm using ExpressiveAnnotations 2.6.4 installed with NuGet.

**Comment by JaroslawWaliszko** [comment]
Hi. I don't really understand why are you using `RequiredIf` attribute on non-nullable `boolean` field. Such a field always **has** a value - either `true` or `false`, so this attribute seems to be useless for me. You should probably use `bool?`? 

The second thing is that you're changing the values of your fields from some custom script. Maybe there is some issue with your `validator` setup (`validator` is given by *jquery.validate*), which is not invoking the validation on currently modified field? If yes, you can enforce such a field validation manually. Just after field value is changed in your script, execute e.g. `$('#HasCivicAddress').valid();`. 

Why manually? EA is relying on *jquery.validate*, and validates any field only, when it is signaled from *jquery.validate* that such a field requires validation (e.g. its value has changed). The logic is a bit more complicated though, when you have some other fields, which state depends on this currently modified one. In such a situation, even if there is no signal from *jquery.validate* to validate a field, its dependencies are still detected and validated by EA (according to `dependencyTriggers` setup) - maybe this behavior should be modified, and also wait for source field to be signaled first - *it's opened for modification*.

Regards
