### ISSUE TITLE
How do I verify an Integer?

### ISSUE THREAD

**Issue by aboesch** [jwaliszko/ExpressiveAnnotations#91]
I want to verify whether a value is an usigned integer e.g. 1 or 2 or 3 or 4
I got IsNumber, but this is valid for example for 3.2 as well.

How can I do that?

Thanks

**Comment by jwaliszko** [comment]
In this case you can probably use `IsDigitChain` method or try to define [your custom alternative](https://github.com/jwaliszko/ExpressiveAnnotations#what-if-there-is-no-built-in-function-i-need).
