### ISSUE TITLE
Doesn't build under Release configurations

### ISSUE THREAD

**Issue by joshnoe** [jwaliszko/ExpressiveAnnotations#92]
The solution doesn't build under any configurations except "debug".

**Comment by jwaliszko** [comment]
It has been done by design, because in `Release` builds the assemblies are being signed. Nevertheless the fact that the private key is required can be annoying (what's more, unless the code is modified, only my key works), I will probably change it.

**Comment by jwaliszko** [comment]
done: https://github.com/jwaliszko/ExpressiveAnnotations/commit/ccf014bb31a1b552bef5cc728248e8c1b6f9996f
