### ISSUE TITLE
Nuget package for DLLs only?

### ISSUE THREAD

**Issue by im1dermike** [jwaliszko/ExpressiveAnnotations#93]
Is there a way to install (via Nuget package) ExpressiveAnnotations.dll and ExpressiveAnnotations.MvcUnobtrusive.dll (and perhaps expressive.annotations.validate.js) ONLY?  I don't want to have to have jQuery and jQuery Validation packages (which contain older references to jQuery) in my project.

**Comment by jwaliszko** [comment]
In order to bypass dependency resolution you can use NuGet with `-IgnoreDependencies` switch, e.g.
```
Install-Package ExpressiveAnnotations -IgnoreDependencies
```

**Comment by im1dermike** [comment]
I guess this was outside of the scope of your (great) ExpressiveAnnotations package, but thanks for teaching me something!
