### ISSUE TITLE
jQuery.Validation.Unobtrusive.Native does not work with ExpressiveAnnotation

### ISSUE THREAD

**Issue by ansaj777** [jwaliszko/ExpressiveAnnotations#98]
I would like to use this https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native with your ExpressiveAnnotation because I am working with dynamic dom.

Everything works correctly just If I use:

```javascript
[AssertThat("StartDate >= WorkStartOn", ErrorMessage = "{0} can not be lower then ({WorkStartOn})")]
[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
[DataType(DataType.Date)]
[Display(Name = "StartDate")]
public DateTime StartDate { get; set; }
```

then I get back this text
```javascript
StartDate can not be lower then (a1e54428-8c27-4817-b92c-a85b49b42277) and not real WorkStartOn date.
```

Can you maybe check why this error?

**Comment by jwaliszko** [comment]
EA has not been designed nor tested in combination with this library. This request is outside of the scope.

It's hard to me to help you without switching to that component and debugging it. I have not much time for that - what I can advice is to turn the `debug` flag on (`ea.settings.debug = true`), and check if there is any meaningful warning shown on the web console output.

**Comment by ansaj777** [comment]
Hi, no problem I can do that. Can you please also tell me where to check this logic? Where is logic which change WorkStartOn with real date?

**Comment by ansaj777** [comment]
And without this library dynamic content can not be validated. I think dynamic content validation is very important. Is not directly connected to you but if ea will work with it would be very nice.

**Comment by jwaliszko** [comment]
Good entry point could be the [`extractValue`](https://github.com/jwaliszko/ExpressiveAnnotations/blob/e90b6d291aea2a8ecf35a6bc42d1c847e232ba9e/src/expressive.annotations.validate.js#L422) method of `modelHelper` object.

**Comment by ansaj777** [comment]
Hello, when I enable debug I found this:

```javascript
TypeError: Cannot read property 'UserFormModel.UserViewModelList[0].UserFormModel.StartDate' of undefined(…)

logger.fail	@	expressive.annotations.validate.js:85
(anonymous function)	@	expressive.annotations.validate.js:663
$.extend.check	@	jquery.validate.js:639
$.extend.element	@	jquery.validate.js:437
$.extend.defaults.onfocusout	@	jquery.validate.js:266
delegate	@	jquery.validate.js:380
n.event.dispatch	@	jquery-2.1.4.min.js:3
r.handle	@	jquery-2.1.4.min.js:3
n.event.trigger	@	jquery-2.1.4.min.js:3
e.event.trigger	@	jquery-migrate-1.2.1.min.js:2
n.event.simulate	@	jquery-2.1.4.min.js:3
c	@	jquery-2.1.4.min.js:3

```

**Comment by jwaliszko** [comment]
Your `parsersMap` is `undefined` probably because your html is corrupted. Normally the html helpers provided by ASP.NET MVC creates proper HTML, based on which EA can work. Correct means all that `data-val-assertthat-*` HTML attributes are there, e.g.
```
<input 
    data-val="true" 
    data-val-assertthat="StartDate can not be lower then (a4d4c136-dc76-43c9-b717-f6f399e7bf60)"
    data-val-assertthat-errfieldsmap="{&quot;WorkStartOn&quot;:&quot;a4d4c136-dc76-43c9-b717-f6f399e7bf60&quot;}"     
    data-val-assertthat-expression="&quot;StartDate >= WorkStartOn&quot;"
    data-val-assertthat-fieldsmap="{&quot;StartDate&quot;:&quot;datetime&quot;,&quot;WorkStartOn&quot;:&quot;datetime&quot;}"
    data-val-assertthat-parsersmap="{&quot;WorkStartOn&quot;:&quot;NonStandardDateParser&quot;}"
```
Check if the [method below](https://github.com/jwaliszko/ExpressiveAnnotations/blob/e90b6d291aea2a8ecf35a6bc42d1c847e232ba9e/src/expressive.annotations.validate.js#L639) has anything in the options argument, i.e.:
```
$.validator.unobtrusive.adapters.add(
    adapter, 
    ['expression', 'fieldsMap', 'constsMap', 'parsersMap', 'errFieldsMap'], 
    function(options) { // options argument should be filled
```
I'd like to emphesize that `data-val-*` attributes are supposed to be generated automatically by some helpers. Otherwise, if you'll change your expression, these `data-val-*` attributes are required to be manually updated as well.

**Comment by ansaj777** [comment]
Thank you. You are right HTML is corrupted. Some of this data-val-* HTML attributes are missing

Can you please write also which are required data-val-required* HTML attributes. The same as for data-val-assertthat*?

**Comment by jwaliszko** [comment]
[The same set of common properties](https://github.com/jwaliszko/ExpressiveAnnotations/blob/e90b6d291aea2a8ecf35a6bc42d1c847e232ba9e/src/ExpressiveAnnotations.MvcUnobtrusive/Validators/ExpressiveValidator.cs#L143-L156).

**Comment by senzacionale** [comment]
Please use this library instead. I modified original code
https://github.com/senzacionale/jQuery.Validation.Unobtrusive.Native

**Comment by ansaj777** [comment]
Thank you. I use your library but is the same. Now I have all required data-val-* HTML attributes but I still get same error.

```javascript
TypeError: Cannot read property 'UserFormModel.UserViewModelList[0].UserFormModel.StartDate' of undefined(…)
```
@ jwaliszko do I need something else also?

```javascript
var parser = params.parsersMap[field]; -> parsersMap is still undefined
```

**Comment by ansaj777** [comment]
Fixed, you can close it! Than you for support.

**Comment by jwaliszko** [comment]
@ansaj777: Good it works. If this is not a problem share your solution in case someone else is looking for it as well.
